import type { PaymentMethod, ReceiptRecord, TransactionStatus } from '@apex-pos/shared-types'
import { Ban, CheckCircle2, FileText, Undo2 } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { useReceipts } from '../hooks/use-receipts'
import {
  fetchBirSettings,
  fetchAuditTrail,
  fetchManagedUsers,
  type BirSettingsResponse,
} from '../lib/api-client'
import { readAuthSession } from '../lib/auth-session'
import { buildCashierOptions, normalizeCashierName } from '../lib/cashier-options'
import { cn } from '../lib/utils'
import { useUiStore } from '../store/ui-store'

const SOFTWARE_NAME = 'BIGTIME POS'
const SOFTWARE_VERSION = '1.0.0'

const DEFAULT_RECEIPT_DATE = ''

const currencyFormatter = new Intl.NumberFormat('en-PH', {
  style: 'currency',
  currency: 'PHP',
  minimumFractionDigits: 2,
})

const countFormatter = new Intl.NumberFormat('en-PH')

const tableGridClass =
  'grid min-w-[980px] grid-cols-[minmax(160px,1.35fr)_minmax(160px,1.1fr)_minmax(150px,1.1fr)_minmax(140px,1fr)_minmax(110px,0.9fr)_minmax(120px,0.9fr)_minmax(130px,0.9fr)_minmax(145px,1fr)] gap-3'

type ReceiptFilters = {
  search: string
  businessDate: string
  paymentMethod: 'ALL' | PaymentMethod
  status: 'ALL' | TransactionStatus
  cashierName: 'ALL' | string
}

const initialFilters: ReceiptFilters = {
  search: '',
  businessDate: DEFAULT_RECEIPT_DATE,
  paymentMethod: 'ALL',
  status: 'ALL',
  cashierName: 'ALL',
}

const paymentLabels: Record<PaymentMethod, string> = {
  CASH: 'Cash',
  CARD: 'Card',
  GCASH: 'GCash',
  MAYA: 'Maya',
  SPLIT: 'Split',
}

const statusLabels: Record<TransactionStatus, string> = {
  COMPLETED: 'Completed',
  VOID: 'Voided',
  RETURNED: 'Returned',
  REFUNDED: 'Refunded',
  HELD: 'Held',
}

const statusClassNames: Record<TransactionStatus, string> = {
  COMPLETED: 'bg-emerald-100 text-emerald-700 ring-1 ring-emerald-200',
  VOID: 'bg-red-100 text-red-700 ring-1 ring-red-200',
  RETURNED: 'bg-amber-100 text-amber-700 ring-1 ring-amber-200',
  REFUNDED: 'bg-amber-100 text-amber-700 ring-1 ring-amber-200',
  HELD: 'bg-[color:var(--border)] text-slate-700 ring-1 ring-slate-300',
}

function formatMoney(value: number) {
  return currencyFormatter.format(value)
}

function formatReceiptNumber(receipt: ReceiptRecord) {
  return `SI ${String(receipt.orNumber).padStart(6, '0')}`
}

function formatReceiptDate(value: string) {
  const date = new Date(value)
  const datePart = date.toLocaleDateString('sv-SE')
  const timePart = date.toLocaleTimeString('en-PH', {
    hour: '2-digit',
    minute: '2-digit',
  })

  return `${datePart} ${timePart}`
}

function matchesBusinessDate(receipt: ReceiptRecord, businessDate: string) {
  if (!businessDate) {
    return true
  }

  return receipt.createdAt.slice(0, 10) === businessDate
}

function csvCell(value: unknown) {
  return `"${String(value ?? '').replaceAll('"', '""')}"`
}

function csvRow(values: unknown[]) {
  return values.map(csvCell).join(',')
}

function buildBirMetadataRows(
  selectedBranch: string,
  birSettings?: BirSettingsResponse,
) {
  const branchLabel =
    selectedBranch === 'all'
      ? 'All Branches'
      : birSettings?.storeName.trim() || selectedBranch
  const address =
    birSettings?.businessAddressLines.filter(Boolean).join(', ') || 'Not configured'
  const tinLabel = birSettings?.vatTin.trim()
    ? `VAT REG TIN ${birSettings.vatTin.trim()}`
    : 'Not configured'
  const session = readAuthSession()
  const generatedBy = session
    ? `${session.user.name} (${session.user.employeeCode})`
    : 'Unknown'

  return [
    csvRow(['Report', 'Sales Invoice Register']),
    csvRow(['Software Name', SOFTWARE_NAME]),
    csvRow(['Software Version', SOFTWARE_VERSION]),
    csvRow([
      'Generated At',
      new Date().toLocaleString('en-PH', { hour12: true, timeZone: 'Asia/Manila' }),
    ]),
    csvRow(['Generated By', generatedBy]),
    csvRow(['Branch', branchLabel]),
    csvRow(['Registered Name', birSettings?.storeName.trim() || 'Not configured']),
    csvRow(['Registered Address', address]),
    csvRow(['TIN', tinLabel]),
    csvRow(['Permit Number', birSettings?.permitNumber.trim() || 'Not configured']),
    csvRow(['Permit Date Issued', birSettings?.permitDateIssued.trim() || 'Not configured']),
    csvRow([
      'Authority to Print Number',
      birSettings?.authorityToPrintNumber.trim() || 'Not configured',
    ]),
    csvRow([
      'Authority to Print Date Issued',
      birSettings?.authorityToPrintDateIssued.trim() || 'Not configured',
    ]),
    csvRow([
      'Approved Serial Range',
      birSettings?.approvedSerialRange.trim() || 'Not configured',
    ]),
    csvRow(['MIN', birSettings?.machineIdentificationNumber.trim() || 'Not configured']),
    csvRow(['Serial Number', birSettings?.serialNumber.trim() || 'Not configured']),
    '',
  ]
}

function downloadReceiptsCsv(
  receipts: ReceiptRecord[],
  options: {
    selectedBranch: string
    birSettings?: BirSettingsResponse
  },
) {
  if (typeof window === 'undefined') {
    return
  }

  const lines = [
    ...buildBirMetadataRows(options.selectedBranch, options.birSettings),
    csvRow([
      'Sales Invoice Number',
      'Date/Time',
      'Customer',
      'Customer TIN',
      'Customer Address',
      'Business Style',
      'Cashier',
      'Terminal',
      'Payment',
      'Status',
      'Subtotal',
      'Vatable Sales',
      'VAT Exempt Sales',
      'Zero Rated Sales',
      'VAT',
      'Discount',
      'Total',
    ]),
    ...receipts.map((receipt) =>
      csvRow([
        formatReceiptNumber(receipt),
        formatReceiptDate(receipt.createdAt),
        receipt.customerName ?? 'Walk-in Customer',
        receipt.customerTin ?? '',
        receipt.customerAddress ?? '',
        receipt.customerBusinessStyle ?? '',
        receipt.cashierName,
        receipt.terminalName ?? receipt.terminalId,
        paymentLabels[receipt.paymentMethod],
        statusLabels[receipt.status],
        receipt.subtotal ?? 0,
        receipt.vatableSales ?? 0,
        receipt.vatExemptSales ?? 0,
        receipt.zeroRatedSales ?? 0,
        receipt.vatAmount ?? 0,
        receipt.discountAmount ?? 0,
        receipt.total,
      ]),
    ),
  ]

  const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'bigtime-pos-receipts.csv'
  link.click()
  URL.revokeObjectURL(url)
}

async function downloadAuditTrailCsv(options: {
  selectedBranch: string
  birSettings?: BirSettingsResponse
}) {
  if (typeof window === 'undefined') {
    return
  }

  const params: Record<string, string> = {}
  if (options.selectedBranch !== 'all') {
    params['branchId'] = options.selectedBranch
  }

  const result = await fetchAuditTrail(params)
  const entries = result.items ?? []

  const lines = [
    ...buildBirMetadataRows(options.selectedBranch, options.birSettings),
    csvRow(['Report', 'Audit Trail Log']),
    '',
    csvRow(['ID', 'Branch', 'User ID', 'Action', 'Table', 'Record ID', 'Date/Time', 'Hash']),
    ...entries.map((entry) =>
      csvRow([
        entry.id,
        entry.branchId,
        entry.userId ?? '',
        entry.action,
        entry.tableName,
        entry.recordId,
        entry.createdAt,
        entry.hash,
      ]),
    ),
  ]

  const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  const ts = new Date().toISOString().slice(0, 10)
  link.download = `bigtime-pos-audit-trail-${ts}.csv`
  link.click()
  URL.revokeObjectURL(url)
}

function ReceiptStatCard({
  label,
  value,
  gradient,
  icon: Icon,
}: {
  label: string
  value: string
  gradient: string
  icon: typeof FileText
}) {
  return (
    <div className={`group relative overflow-hidden rounded-[24px] bg-gradient-to-br ${gradient} p-5 shadow-md transition hover:shadow-lg hover:-translate-y-0.5`}>
      <div className="flex items-start justify-between">
        <div className="space-y-2">
          <p className="text-[0.78rem] font-semibold uppercase tracking-[0.16em] text-white/75">{label}</p>
          <p className="section-title text-[2.1rem] font-bold leading-none tracking-[-0.03em] text-white">{value}</p>
        </div>
        <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-white/20 transition group-hover:scale-105 group-hover:bg-white/25">
          <Icon className="h-5 w-5 text-white" />
        </div>
      </div>
      <div className="pointer-events-none absolute -right-5 -bottom-5 h-24 w-24 rounded-full bg-white/10 transition group-hover:bg-white/15" />
    </div>
  )
}

function ReceiptInfoTile({
  label,
  value,
}: {
  label: string
  value: string
}) {
  return (
    <div className="rounded-2xl bg-[color:var(--surface-soft)] p-3">
      <p className="text-sm text-[color:var(--muted)]">{label}</p>
      <p className="font-semibold text-[color:var(--ink)]">{value}</p>
    </div>
  )
}

function ReceiptListCard({
  receipt,
  cashierName,
  isSelected,
  onView,
  onReprint,
}: {
  receipt: ReceiptRecord
  cashierName: string
  isSelected: boolean
  onView: (receiptId: string) => void
  onReprint: (receiptId: string) => void
}) {
  return (
    <article
      className={cn(
        'dashboard-soft-panel dashboard-soft-panel-hover rounded-[22px] border p-3 transition-colors',
        isSelected ? 'border-blue-400/65 bg-[color:var(--accent-soft)]' : 'border-[color:var(--border)]',
      )}
    >
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="space-y-1">
          <p className="text-sm font-semibold text-[color:var(--ink)]">{formatReceiptNumber(receipt)}</p>
          <p className="text-sm text-[color:var(--muted)]">{formatReceiptDate(receipt.createdAt)}</p>
        </div>
        <span
          className={cn(
            'inline-flex w-fit rounded-full px-3 py-1 text-xs font-semibold',
            statusClassNames[receipt.status],
          )}
        >
          {statusLabels[receipt.status]}
        </span>
      </div>

      <div className="mt-3 grid gap-2.5 sm:grid-cols-2">
        <div>
          <p className="text-xs uppercase tracking-[0.16em] text-[color:var(--muted)]">Customer</p>
          <p className="mt-1 text-sm text-[color:var(--muted)]">{receipt.customerName ?? 'Walk-in Customer'}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.16em] text-[color:var(--muted)]">Cashier</p>
          <p className="mt-1 text-sm text-[color:var(--muted)]">{cashierName}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.16em] text-[color:var(--muted)]">Payment</p>
          <p className="mt-1 text-sm text-[color:var(--muted)]">{paymentLabels[receipt.paymentMethod]}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.16em] text-[color:var(--muted)]">Total</p>
          <p className="mt-1 text-base font-semibold text-[color:var(--ink)]">{formatMoney(receipt.total)}</p>
        </div>
      </div>

      <div className="mt-3 flex flex-col gap-2 sm:flex-row">
        <button
          type="button"
          onClick={() => onView(receipt.id)}
          className="rounded-xl border border-[color:var(--border)] px-3 py-1.5 text-xs font-medium text-[color:var(--muted)] transition hover:bg-[color:var(--surface-soft)]"
        >
          View Receipt
        </button>
        <button
          type="button"
          onClick={() => onReprint(receipt.id)}
          className="rounded-xl border border-[color:var(--border)] px-3 py-1.5 text-xs font-medium text-[color:var(--muted)] transition hover:bg-[color:var(--surface-soft)]"
        >
          Reprint
        </button>
      </div>
    </article>
  )
}

export function ReceiptsPage() {
  const selectedBranch = useUiStore((state) => state.selectedBranch)
  const receiptsQuery = useReceipts(selectedBranch)
  const receipts = useMemo(() => receiptsQuery.data ?? [], [receiptsQuery.data])
  const birSettingsQuery = useQuery({
    queryKey: ['bir-settings', selectedBranch],
    queryFn: () => fetchBirSettings(selectedBranch),
    enabled: selectedBranch !== 'all',
  })
  const managedUsersQuery = useQuery({
    queryKey: ['managed-users', selectedBranch],
    queryFn: () => fetchManagedUsers(selectedBranch),
  })
  const managedUsers = managedUsersQuery.data ?? []

  const [draftFilters, setDraftFilters] = useState<ReceiptFilters>(initialFilters)
  const [appliedFilters, setAppliedFilters] = useState<ReceiptFilters>(initialFilters)
  const [selectedReceiptId, setSelectedReceiptId] = useState<string | null>(null)
  const [downloadingAuditTrail, setDownloadingAuditTrail] = useState(false)

  const cashierOptions = useMemo(
    () =>
      buildCashierOptions({
        receipts,
        managedUsers,
        extraValues: [
          draftFilters.cashierName !== 'ALL' ? draftFilters.cashierName : '',
          appliedFilters.cashierName !== 'ALL' ? appliedFilters.cashierName : '',
        ],
      }),
    [appliedFilters.cashierName, draftFilters.cashierName, managedUsers, receipts],
  )

  const filteredReceipts = useMemo(() => {
    const searchTerm = appliedFilters.search.trim().toLowerCase()

    return receipts.filter((receipt) => {
      if (!matchesBusinessDate(receipt, appliedFilters.businessDate)) {
        return false
      }

      if (
        appliedFilters.paymentMethod !== 'ALL' &&
        receipt.paymentMethod !== appliedFilters.paymentMethod
      ) {
        return false
      }

      if (appliedFilters.status !== 'ALL' && receipt.status !== appliedFilters.status) {
        return false
      }

      if (
        appliedFilters.cashierName !== 'ALL' &&
        normalizeCashierName(receipt.cashierName, managedUsers) !==
          appliedFilters.cashierName
      ) {
        return false
      }

      if (!searchTerm) {
        return true
      }

      return [
        formatReceiptNumber(receipt),
        receipt.refNumber,
        receipt.customerName ?? '',
        normalizeCashierName(receipt.cashierName, managedUsers),
        receipt.terminalName ?? '',
      ]
        .join(' ')
        .toLowerCase()
        .includes(searchTerm)
    })
  }, [appliedFilters, managedUsers, receipts])

  const selectedReceipt = useMemo(() => {
    if (filteredReceipts.length === 0) {
      return null
    }

    if (selectedReceiptId) {
      const selected = filteredReceipts.find((receipt) => receipt.id === selectedReceiptId)
      if (selected) {
        return selected
      }
    }

    return filteredReceipts[0]
  }, [filteredReceipts, selectedReceiptId])

  const receiptStats = useMemo(() => {
    const base = {
      total: filteredReceipts.length,
      completed: 0,
      refunded: 0,
      voided: 0,
    }

    return filteredReceipts.reduce((stats, receipt) => {
      if (receipt.status === 'COMPLETED') {
        stats.completed += 1
      }

      if (receipt.status === 'REFUNDED' || receipt.status === 'RETURNED') {
        stats.refunded += 1
      }

      if (receipt.status === 'VOID') {
        stats.voided += 1
      }

      return stats
    }, base)
  }, [filteredReceipts])

  const handleViewReceipt = (receiptId: string) => {
    setSelectedReceiptId(receiptId)
  }

  const handleReprintReceipt = (receiptId: string) => {
    setSelectedReceiptId(receiptId)

    if (typeof window !== 'undefined') {
      window.print()
    }
  }

  return (
    <div className="space-y-6 text-[color:var(--ink)]">
      <section className="glass-panel dashboard-panel-hover p-5 sm:p-6 md:p-7">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-[color:var(--ink)] sm:text-3xl">
              Receipt Management
            </h1>
            <p className="mt-1 text-sm text-[color:var(--muted)]">
              Search, review, reprint, refund, and track POS receipts across all terminals.
            </p>
          </div>
          <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap">
            <button
              type="button"
              onClick={() =>
                downloadReceiptsCsv(filteredReceipts, {
                  selectedBranch,
                  birSettings: birSettingsQuery.data,
                })
              }
              className="w-full rounded-2xl border border-[color:var(--border)] bg-[color:var(--panel)] px-4 py-2.5 text-sm font-medium text-[color:var(--muted)] shadow-sm transition hover:border-slate-300 hover:bg-[color:var(--surface-soft)] sm:w-auto"
            >
              Export CSV
            </button>
            <button
              type="button"
              disabled={downloadingAuditTrail}
              onClick={async () => {
                setDownloadingAuditTrail(true)
                try {
                  await downloadAuditTrailCsv({
                    selectedBranch,
                    birSettings: birSettingsQuery.data,
                  })
                } finally {
                  setDownloadingAuditTrail(false)
                }
              }}
              className="w-full rounded-2xl border border-[color:var(--border)] bg-[color:var(--panel)] px-4 py-2.5 text-sm font-medium text-[color:var(--muted)] shadow-sm transition hover:border-slate-300 hover:bg-[color:var(--surface-soft)] disabled:opacity-50 sm:w-auto"
            >
              {downloadingAuditTrail ? 'Exporting…' : 'Export Audit Trail'}
            </button>
            <button
              type="button"
              onClick={() => {
                if (typeof window !== 'undefined') {
                  window.print()
                }
              }}
              className="w-full rounded-2xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-slate-800 sm:w-auto"
            >
              Download PDF
            </button>
          </div>
        </div>
      </section>

      <section className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-4">
        <ReceiptStatCard
          label="Today's Receipts"
          value={countFormatter.format(receiptStats.total)}
          gradient="from-[#52d4cc] to-[#28a89a]"
          icon={FileText}
        />
        <ReceiptStatCard
          label="Completed"
          value={countFormatter.format(receiptStats.completed)}
          gradient="from-[#4ade80] to-[#16a34a]"
          icon={CheckCircle2}
        />
        <ReceiptStatCard
          label="Refunded"
          value={countFormatter.format(receiptStats.refunded)}
          gradient="from-[#ff9b6a] to-[#f06040]"
          icon={Undo2}
        />
        <ReceiptStatCard
          label="Voided"
          value={countFormatter.format(receiptStats.voided)}
          gradient="from-[#fb7185] to-[#e11d48]"
          icon={Ban}
        />
      </section>

      <section className="glass-panel dashboard-panel-hover p-5">
        <div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-6">
          <input
            value={draftFilters.search}
            onChange={(event) =>
              setDraftFilters((current) => ({ ...current, search: event.target.value }))
            }
            className="rounded-2xl border border-[color:var(--border)] bg-[color:var(--panel)] px-4 py-3 text-sm text-[color:var(--ink)] outline-none transition placeholder:text-[color:var(--muted)] focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
            placeholder="Search receipt #, customer, cashier"
          />
          <input
            value={draftFilters.businessDate}
            onChange={(event) =>
              setDraftFilters((current) => ({ ...current, businessDate: event.target.value }))
            }
            className="rounded-2xl border border-[color:var(--border)] bg-[color:var(--panel)] px-4 py-3 text-sm text-[color:var(--ink)] outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
            type="date"
          />
          <select
            value={draftFilters.paymentMethod}
            onChange={(event) =>
              setDraftFilters((current) => ({
                ...current,
                paymentMethod: event.target.value as ReceiptFilters['paymentMethod'],
              }))
            }
            className="rounded-2xl border border-[color:var(--border)] bg-[color:var(--panel)] px-4 py-3 text-sm text-[color:var(--ink)] outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
          >
            <option value="ALL">All Payment Methods</option>
            {Object.entries(paymentLabels).map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>
          <select
            value={draftFilters.status}
            onChange={(event) =>
              setDraftFilters((current) => ({
                ...current,
                status: event.target.value as ReceiptFilters['status'],
              }))
            }
            className="rounded-2xl border border-[color:var(--border)] bg-[color:var(--panel)] px-4 py-3 text-sm text-[color:var(--ink)] outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
          >
            <option value="ALL">All Status</option>
            {Object.entries(statusLabels).map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>
          <select
            value={draftFilters.cashierName}
            onChange={(event) =>
              setDraftFilters((current) => ({
                ...current,
                cashierName: event.target.value,
              }))
            }
            className="rounded-2xl border border-[color:var(--border)] bg-[color:var(--panel)] px-4 py-3 text-sm text-[color:var(--ink)] outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
          >
            <option value="ALL">All Cashiers</option>
            {cashierOptions.map((cashierName) => (
              <option key={cashierName} value={cashierName}>
                {cashierName}
              </option>
            ))}
          </select>
          <div className="flex flex-col gap-3 sm:flex-row">
            <button
              type="button"
              onClick={() => setAppliedFilters(draftFilters)}
              className="flex-1 rounded-2xl bg-blue-600 px-4 py-3 text-sm font-medium text-white transition hover:bg-blue-700"
            >
              Apply Filters
            </button>
            <button
              type="button"
              onClick={() => {
                setDraftFilters(initialFilters)
                setAppliedFilters(initialFilters)
              }}
              className="rounded-2xl border border-[color:var(--border)] px-4 py-3 text-sm font-medium text-[color:var(--muted)] transition hover:bg-[color:var(--surface-soft)]"
            >
              Reset
            </button>
          </div>
        </div>
      </section>

      <section className="grid gap-6 2xl:grid-cols-[minmax(0,1.45fr)_minmax(360px,1fr)]">
        <article className="min-w-0 glass-panel dashboard-panel-hover p-5">
          <div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div>
              <h2 className="text-xl font-semibold text-[color:var(--ink)]">Receipt List</h2>
              <p className="text-sm text-[color:var(--muted)]">
                Latest transactions from all terminals
              </p>
            </div>
            <button
              type="button"
              onClick={() => void receiptsQuery.refetch()}
              className="rounded-2xl border border-[color:var(--border)] px-4 py-2 text-sm font-medium text-[color:var(--muted)] transition hover:bg-[color:var(--surface-soft)]"
            >
              Refresh
            </button>
          </div>
          {receiptsQuery.isError ? (
            <div className="mb-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
              Unable to load live receipts from the backend. Check API connection and branch filter.
            </div>
          ) : null}
          {receiptsQuery.isFetching ? (
            <p className="mb-3 text-xs text-[color:var(--muted)]">Syncing latest receipts...</p>
          ) : null}

          <div className="max-h-[680px] space-y-2 overflow-y-auto pr-1 2xl:hidden">
            {filteredReceipts.length === 0 ? (
              <div className="rounded-[24px] border border-[color:var(--border)] bg-[color:var(--surface-soft)] px-6 py-10 text-center text-sm text-[color:var(--muted)]">
                No receipts matched the current filters.
              </div>
            ) : (
              filteredReceipts.map((receipt) => (
                <ReceiptListCard
                  key={receipt.id}
                  receipt={receipt}
                  cashierName={normalizeCashierName(receipt.cashierName, managedUsers)}
                  isSelected={receipt.id === selectedReceipt?.id}
                  onView={handleViewReceipt}
                  onReprint={handleReprintReceipt}
                />
              ))
            )}
          </div>

          <div className="hidden overflow-hidden rounded-[24px] border border-[color:var(--border)] 2xl:block">
            <div className="max-h-[680px] overflow-auto overscroll-contain">
              <div className={cn(tableGridClass, 'sticky top-0 z-10 bg-[color:var(--header-tint)] px-4 py-3 text-xs font-semibold uppercase tracking-[0.22em] text-[color:var(--muted)]')}>
                <div>Receipt #</div>
                <div>Date/Time</div>
                <div>Customer</div>
                <div>Cashier</div>
                <div>Payment</div>
                <div>Status</div>
                <div>Total</div>
                <div>Actions</div>
              </div>

              {filteredReceipts.length === 0 ? (
                <div className="px-6 py-10 text-center text-sm text-[color:var(--muted)]">
                  No receipts matched the current filters.
                </div>
              ) : (
                filteredReceipts.map((receipt) => (
                  <div
                    key={receipt.id}
                    className={cn(
                      tableGridClass,
                      'border-t border-[color:var(--border)] px-4 py-3 text-sm transition',
                      receipt.id === selectedReceipt?.id ? 'bg-[color:var(--surface-soft)]' : 'bg-[color:var(--panel)]',
                    )}
                  >
                    <div className="font-semibold text-[color:var(--ink)]">
                      {formatReceiptNumber(receipt)}
                    </div>
                    <div className="text-[color:var(--muted)]">{formatReceiptDate(receipt.createdAt)}</div>
                    <div className="text-[color:var(--muted)]">
                      {receipt.customerName ?? 'Walk-in Customer'}
                    </div>
                    <div className="text-[color:var(--muted)]">
                      {normalizeCashierName(receipt.cashierName, managedUsers)}
                    </div>
                    <div className="text-[color:var(--muted)]">
                      {paymentLabels[receipt.paymentMethod]}
                    </div>
                    <div>
                      <span
                        className={cn(
                          'inline-flex rounded-full px-3 py-1 text-xs font-semibold',
                          statusClassNames[receipt.status],
                        )}
                      >
                        {statusLabels[receipt.status]}
                      </span>
                    </div>
                    <div className="font-semibold text-[color:var(--ink)]">{formatMoney(receipt.total)}</div>
                    <div className="flex flex-wrap gap-2">
                      <button
                        type="button"
                        onClick={() => handleViewReceipt(receipt.id)}
                        className="rounded-xl border border-[color:var(--border)] px-3 py-1 text-xs font-medium text-[color:var(--muted)] transition hover:bg-[color:var(--surface-soft)]"
                      >
                        View
                      </button>
                      <button
                        type="button"
                        onClick={() => handleReprintReceipt(receipt.id)}
                        className="rounded-xl border border-[color:var(--border)] px-3 py-1 text-xs font-medium text-[color:var(--muted)] transition hover:bg-[color:var(--surface-soft)]"
                      >
                        Reprint
                      </button>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </article>

        <div className="space-y-6">
          <article className="glass-panel dashboard-panel-hover p-5 2xl:sticky 2xl:top-4">
            {selectedReceipt ? (
              <>
                <div className="mb-4 flex items-start justify-between gap-3">
                  <div>
                    <h2 className="text-xl font-semibold text-[color:var(--ink)]">Receipt Details</h2>
                    <p className="text-sm text-[color:var(--muted)]">Full transaction drill-down</p>
                  </div>
                  <span
                    className={cn(
                      'inline-flex rounded-full px-3 py-1 text-xs font-semibold',
                      statusClassNames[selectedReceipt.status],
                    )}
                  >
                    {statusLabels[selectedReceipt.status]}
                  </span>
                </div>

                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  <ReceiptInfoTile
                    label="Receipt #"
                    value={formatReceiptNumber(selectedReceipt)}
                  />
                  <ReceiptInfoTile
                    label="Date/Time"
                    value={formatReceiptDate(selectedReceipt.createdAt)}
                  />
                  <ReceiptInfoTile
                    label="Cashier"
                    value={normalizeCashierName(selectedReceipt.cashierName, managedUsers)}
                  />
                  <ReceiptInfoTile
                    label="Terminal"
                    value={selectedReceipt.terminalName ?? selectedReceipt.terminalId}
                  />
                  <ReceiptInfoTile
                    label="Customer"
                    value={selectedReceipt.customerName ?? 'Walk-in Customer'}
                  />
                  <ReceiptInfoTile
                    label="Customer TIN"
                    value={selectedReceipt.customerTin ?? 'Not provided'}
                  />
                  <ReceiptInfoTile
                    label="Business style"
                    value={selectedReceipt.customerBusinessStyle ?? 'Not provided'}
                  />
                  <ReceiptInfoTile
                    label="Payment"
                    value={paymentLabels[selectedReceipt.paymentMethod]}
                  />
                </div>

                <div className="mt-4 rounded-2xl bg-[color:var(--surface-soft)] p-4">
                  <p className="text-sm text-[color:var(--muted)]">Customer address</p>
                  <p className="mt-1 text-sm font-medium text-[color:var(--ink)]">
                    {selectedReceipt.customerAddress ?? 'Not provided'}
                  </p>
                </div>

                <div className="mt-5 overflow-hidden rounded-2xl border border-[color:var(--border)]">
                  <div className="border-b border-[color:var(--border)] px-4 py-3 text-sm font-semibold text-[color:var(--ink)]">
                    Items Purchased
                  </div>
                  <div className="space-y-3 px-4 py-4">
                    {(selectedReceipt.items ?? []).map((item) => (
                      <div key={item.name} className="flex items-center justify-between gap-4 text-sm">
                        <div>
                          <p className="font-medium text-[color:var(--ink)]">{item.name}</p>
                          <p className="text-[color:var(--muted)]">Qty: {item.qty}</p>
                        </div>
                        <p className="font-semibold text-[color:var(--ink)]">
                          {formatMoney(item.qty * item.price)}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="mt-5 space-y-2 rounded-2xl bg-[color:var(--surface-soft)] p-4 text-sm">
                  <div className="flex justify-between gap-4">
                    <span className="text-[color:var(--muted)]">Subtotal</span>
                    <span className="font-medium text-[color:var(--ink)]">
                      {formatMoney(selectedReceipt.subtotal ?? selectedReceipt.total)}
                    </span>
                  </div>
                  <div className="flex justify-between gap-4">
                    <span className="text-[color:var(--muted)]">VAT</span>
                    <span className="font-medium text-[color:var(--ink)]">
                      {formatMoney(selectedReceipt.vatAmount ?? 0)}
                    </span>
                  </div>
                  <div className="flex justify-between gap-4">
                    <span className="text-[color:var(--muted)]">Discount</span>
                    <span className="font-medium text-[color:var(--ink)]">
                      {formatMoney(selectedReceipt.discountAmount ?? 0)}
                    </span>
                  </div>
                  <div className="flex justify-between gap-4">
                    <span className="text-[color:var(--muted)]">Change</span>
                    <span className="font-medium text-[color:var(--ink)]">
                      {formatMoney(selectedReceipt.changeAmount ?? 0)}
                    </span>
                  </div>
                  <div className="flex justify-between gap-4 border-t border-[color:var(--border)] pt-2 text-base font-semibold text-[color:var(--ink)]">
                    <span>Total</span>
                    <span>{formatMoney(selectedReceipt.total)}</span>
                  </div>
                </div>

                <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:flex-wrap">
                  <button
                    type="button"
                    onClick={() => {
                      if (typeof window !== 'undefined') {
                        window.print()
                      }
                    }}
                    className="rounded-2xl bg-slate-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-slate-800"
                  >
                    Reprint Receipt
                  </button>
                  <button
                    type="button"
                    className="rounded-2xl bg-amber-500 px-4 py-2 text-sm font-medium text-white transition hover:bg-amber-600"
                  >
                    Process Refund
                  </button>
                  <button
                    type="button"
                    className="rounded-2xl border border-[color:var(--border)] px-4 py-2 text-sm font-medium text-[color:var(--muted)] transition hover:bg-[color:var(--surface-soft)]"
                  >
                    Send to Email
                  </button>
                </div>
              </>
            ) : (
              <div className="rounded-2xl bg-[color:var(--surface-soft)] px-5 py-8 text-sm text-[color:var(--muted)]">
                Select a receipt from the list to inspect the full transaction details.
              </div>
            )}
          </article>

          <article className="glass-panel dashboard-panel-hover p-5">
            <h2 className="text-xl font-semibold text-[color:var(--ink)]">Audit Trail</h2>
            <p className="mb-4 text-sm text-[color:var(--muted)]">
              Every action linked to this receipt
            </p>
            <div className="space-y-3">
              {(selectedReceipt?.timeline ?? []).map((entry) => (
                <div
                  key={entry}
                  className="rounded-2xl bg-[color:var(--surface-soft)] p-3 text-sm text-[color:var(--muted)]"
                >
                  {entry}
                </div>
              ))}
            </div>
          </article>
        </div>
      </section>
    </div>
  )
}




